// frontend/src/app/layout/sidebar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { AppStateService } from '../core/app-state.service';
import { Environment } from '../core/models';
import { EnvironmentItemComponent } from '../environments/environment-item.component';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [EnvironmentItemComponent],
  template: `
    <aside class="sidebar">
      <div class="sidebar-header">
        <span>Environments</span>
        <button class="icon-btn" type="button" title="New Environment" (click)="createEnvironment.emit()">+</button>
      </div>
      <div class="sidebar-list">
        @if (state.environments().length === 0) {
          <div class="sidebar-empty">No environments yet.</div>
        }
        @for (env of state.environments(); track env.id) {
          <app-environment-item
            [environment]="env"
            [status]="state.statuses()[env.id]"
            [selected]="env.id === state.selectedEnvironmentId()"
            (select)="state.selectEnvironment(env.id)"
            (edit)="editEnvironment.emit(env)"
            (duplicate)="state.duplicateEnvironment(env.id)"
            (delete)="onDelete(env)"
          />
        }
      </div>
    </aside>
  `
})
export class SidebarComponent {
  @Output() createEnvironment = new EventEmitter<void>();
  @Output() editEnvironment = new EventEmitter<Environment>();

  constructor(public state: AppStateService) {}

  onDelete(env: Environment): void {
    if (window.confirm(`Delete environment "${env.name}"?`)) {
      this.state.deleteEnvironment(env.id);
    }
  }
}

// frontend/src/components/Layout/Sidebar.tsx
import { useAppContext } from "../../context/AppContext";
import type { Environment } from "../../types";
import EnvironmentItem from "../Environments/EnvironmentItem";

interface Props {
  onCreateEnvironment: () => void;
  onEditEnvironment: (env: Environment) => void;
}

export default function Sidebar({ onCreateEnvironment, onEditEnvironment }: Props) {
  const { environments, statuses, selectedEnvironmentId, selectEnvironment, duplicateEnvironment, deleteEnvironment } =
    useAppContext();

  return (
    <aside className="sidebar">
      <div className="sidebar-header">
        <span>Environments</span>
        <button className="icon-btn" title="New Environment" onClick={onCreateEnvironment}>
          +
        </button>
      </div>
      <div className="sidebar-list">
        {environments.length === 0 && <div className="sidebar-empty">No environments yet.</div>}
        {environments.map((env) => (
          <EnvironmentItem
            key={env.id}
            environment={env}
            status={statuses[env.id]}
            selected={env.id === selectedEnvironmentId}
            onSelect={() => selectEnvironment(env.id)}
            onEdit={() => onEditEnvironment(env)}
            onDuplicate={() => duplicateEnvironment(env.id)}
            onDelete={() => {
              if (window.confirm(`Delete environment "${env.name}"?`)) {
                deleteEnvironment(env.id);
              }
            }}
          />
        ))}
      </div>
    </aside>
  );
}
