// frontend/src/app/layout/toolbar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { AppStateService } from '../core/app-state.service';
import { IconComponent } from '../shared/icon.component';

@Component({
  selector: 'app-toolbar',
  standalone: true,
  imports: [IconComponent],
  template: `
    <header class="toolbar">
      <div class="toolbar-brand">
        <span class="toolbar-brand-mark">BP</span>
        <span>BatchPilot</span>
      </div>
      <div class="toolbar-actions">
        <button
          class="btn"
          [disabled]="!state.selectedEnvironment() || connected() || busy()"
          (click)="connectSelected()"
        >
          <app-icon name="plug" size="14" />
          Connect
        </button>
        <button class="btn" [disabled]="!state.selectedEnvironment() || !connected()" (click)="disconnectSelected()">
          <app-icon name="plug-off" size="14" />
          Disconnect
        </button>
        <button class="btn" [disabled]="!state.selectedEnvironment() || busy()" (click)="reconnectSelected()">
          <app-icon name="refresh" size="14" />
          Reconnect
        </button>
        <div class="toolbar-sep"></div>
        <button class="btn" [disabled]="!state.selectedEnvironment()" (click)="newTerminal.emit()">
          <app-icon name="terminal" size="14" />
          Terminal
        </button>
        <button class="btn" [disabled]="!state.selectedEnvironment() || !connected()" (click)="openFiles.emit()">
          <app-icon name="folder" size="14" />
          Files
        </button>
        <button
          class="btn"
          [disabled]="!state.selectedEnvironment() || !connected()"
          (click)="openQuickExecute.emit()"
        >
          <app-icon name="play" size="14" />
          Quick Execute
        </button>
        <button
          class="btn"
          [disabled]="!state.selectedEnvironment() || !connected()"
          (click)="openApplications.emit()"
        >
          <app-icon name="activity" size="14" />
          Applications
        </button>
        <button
          class="btn"
          [disabled]="!state.selectedEnvironment() || !connected()"
          (click)="openStageTracker.emit()"
        >
          <app-icon name="file-search" size="14" />
          Stage Tracker
        </button>
        <div class="toolbar-sep"></div>
        <button class="btn icon-btn" title="Settings" (click)="openSettings.emit()">
          <app-icon name="settings" size="16" />
        </button>
      </div>
    </header>
  `
})
export class ToolbarComponent {
  @Output() newTerminal = new EventEmitter<void>();
  @Output() openFiles = new EventEmitter<void>();
  @Output() openQuickExecute = new EventEmitter<void>();
  @Output() openSettings = new EventEmitter<void>();
  @Output() openApplications = new EventEmitter<void>();
  @Output() openStageTracker = new EventEmitter<void>();

  constructor(public state: AppStateService) {}

  connected(): boolean {
    return this.state.selectedStatus()?.state === 'CONNECTED';
  }

  busy(): boolean {
    const s = this.state.selectedStatus()?.state;
    return s === 'CONNECTING' || s === 'RECONNECTING';
  }

  connectSelected(): void {
    const env = this.state.selectedEnvironment();
    if (env) this.state.connect(env.id);
  }

  disconnectSelected(): void {
    const env = this.state.selectedEnvironment();
    if (env) this.state.disconnect(env.id);
  }

  reconnectSelected(): void {
    const env = this.state.selectedEnvironment();
    if (env) this.state.reconnect(env.id);
  }
}

// frontend/src/components/Layout/Toolbar.tsx
import { useAppContext } from "../../context/AppContext";
import type { ConnectionStatus, Environment } from "../../types";

interface Props {
  selectedEnvironment: Environment | null;
  status?: ConnectionStatus;
  onNewTerminal: () => void;
  onOpenFiles: () => void;
  onOpenQuickExecute: () => void;
  onOpenSettings: () => void;
}

export default function Toolbar({
  selectedEnvironment,
  status,
  onNewTerminal,
  onOpenFiles,
  onOpenQuickExecute,
  onOpenSettings
}: Props) {
  const { connect, disconnect, reconnect } = useAppContext();
  const connected = status?.state === "CONNECTED";
  const busy = status?.state === "CONNECTING" || status?.state === "RECONNECTING";

  return (
    <header className="toolbar">
      <div className="toolbar-brand">BatchPilot</div>
      <div className="toolbar-actions">
        <button
          className="btn"
          disabled={!selectedEnvironment || connected || busy}
          onClick={() => selectedEnvironment && connect(selectedEnvironment.id)}
        >
          Connect
        </button>
        <button
          className="btn"
          disabled={!selectedEnvironment || !connected}
          onClick={() => selectedEnvironment && disconnect(selectedEnvironment.id)}
        >
          Disconnect
        </button>
        <button
          className="btn"
          disabled={!selectedEnvironment || busy}
          onClick={() => selectedEnvironment && reconnect(selectedEnvironment.id)}
        >
          Reconnect
        </button>
        <div className="toolbar-sep" />
        <button className="btn" disabled={!selectedEnvironment} onClick={onNewTerminal}>
          + Terminal
        </button>
        <button className="btn" disabled={!selectedEnvironment || !connected} onClick={onOpenFiles}>
          Files
        </button>
        <button className="btn" disabled={!selectedEnvironment || !connected} onClick={onOpenQuickExecute}>
          Quick Execute
        </button>
        <div className="toolbar-sep" />
        <button className="btn" onClick={onOpenSettings}>
          Settings
        </button>
      </div>
    </header>
  );
}
