// frontend/src/components/FileManager/FileManagerPanel.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { api } from "../../api/client";
import type { FileEntry } from "../../types";

interface Props {
  environmentId: string;
}

type ViewMode = "table" | "grid";

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB", "TB"];
  let value = bytes / 1024;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex++;
  }
  return `${value.toFixed(1)} ${units[unitIndex]}`;
}

export default function FileManagerPanel({ environmentId }: Props) {
  const [path, setPath] = useState(".");
  const [entries, setEntries] = useState<FileEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [view, setView] = useState<ViewMode>("table");
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [dragOver, setDragOver] = useState(false);
  const [uploadProgress, setUploadProgress] = useState<{ loaded: number; total: number } | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const list = await api.files.list(environmentId, path, search || undefined);
      setEntries(list);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to list directory");
    } finally {
      setLoading(false);
    }
  }, [environmentId, path, search]);

  useEffect(() => {
    load();
    setSelected(new Set());
  }, [load]);

  const navigateInto = (entry: FileEntry) => {
    if (entry.directory) {
      setPath(entry.path);
    }
  };

  const navigateUp = () => {
    if (path === "." || path === "/") return;
    const trimmed = path.replace(/\/+$/, "");
    const parent = trimmed.substring(0, trimmed.lastIndexOf("/"));
    setPath(parent === "" ? "/" : parent);
  };

  const toggleSelect = (entryPath: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(entryPath)) next.delete(entryPath);
      else next.add(entryPath);
      return next;
    });
  };

  const uploadFiles = async (files: File[]) => {
    if (files.length === 0) return;
    setUploadProgress({ loaded: 0, total: 1 });
    try {
      await api.files.upload(environmentId, path, files, (loaded, total) => setUploadProgress({ loaded, total }));
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Upload failed");
    } finally {
      setUploadProgress(null);
    }
  };

  const downloadSelected = () => {
    entries
      .filter((entry) => selected.has(entry.path) && !entry.directory)
      .forEach((entry) => {
        const a = document.createElement("a");
        a.href = api.files.downloadUrl(environmentId, entry.path);
        a.download = entry.name;
        a.click();
      });
  };

  return (
    <div
      className={`file-manager ${dragOver ? "file-manager-drag" : ""}`}
      onDragOver={(e) => {
        e.preventDefault();
        setDragOver(true);
      }}
      onDragLeave={() => setDragOver(false)}
      onDrop={(e) => {
        e.preventDefault();
        setDragOver(false);
        uploadFiles(Array.from(e.dataTransfer.files));
      }}
    >
      <div className="file-manager-toolbar">
        <button className="btn" onClick={navigateUp} disabled={path === "." || path === "/"}>
          ↑ Up
        </button>
        <input className="file-manager-path" value={path} onChange={(e) => setPath(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} />
        <input
          className="file-manager-search"
          placeholder="Search…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <button className="btn" onClick={() => fileInputRef.current?.click()}>
          Upload
        </button>
        <input
          ref={fileInputRef}
          type="file"
          multiple
          hidden
          onChange={(e) => uploadFiles(Array.from(e.target.files ?? []))}
        />
        <button className="btn" disabled={selected.size === 0} onClick={downloadSelected}>
          Download ({selected.size})
        </button>
        <div className="view-toggle">
          <button className={view === "table" ? "active" : ""} onClick={() => setView("table")}>
            ☰
          </button>
          <button className={view === "grid" ? "active" : ""} onClick={() => setView("grid")}>
            ▦
          </button>
        </div>
      </div>

      {uploadProgress && (
        <div className="upload-progress">
          <div
            className="upload-progress-bar"
            style={{ width: `${Math.round((uploadProgress.loaded / uploadProgress.total) * 100)}%` }}
          />
        </div>
      )}

      {error && <div className="form-error">{error}</div>}
      {loading && <div className="file-manager-loading">Loading…</div>}

      {!loading && view === "table" && (
        <table className="file-table">
          <thead>
            <tr>
              <th></th>
              <th>Name</th>
              <th>Size</th>
              <th>Modified</th>
              <th>Permissions</th>
            </tr>
          </thead>
          <tbody>
            {entries.map((entry) => (
              <tr
                key={entry.path}
                className={selected.has(entry.path) ? "row-selected" : ""}
                onDoubleClick={() => navigateInto(entry)}
              >
                <td>
                  <input type="checkbox" checked={selected.has(entry.path)} onChange={() => toggleSelect(entry.path)} />
                </td>
                <td>
                  {entry.directory ? "📁" : "📄"} {entry.name}
                </td>
                <td>{entry.directory ? "—" : formatSize(entry.size)}</td>
                <td>{entry.lastModified ? new Date(entry.lastModified).toLocaleString() : "—"}</td>
                <td>{entry.permissions}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      {!loading && view === "grid" && (
        <div className="file-grid">
          {entries.map((entry) => (
            <div
              key={entry.path}
              className={`file-grid-item ${selected.has(entry.path) ? "row-selected" : ""}`}
              onClick={() => toggleSelect(entry.path)}
              onDoubleClick={() => navigateInto(entry)}
            >
              <div className="file-grid-icon">{entry.directory ? "📁" : "📄"}</div>
              <div className="file-grid-name">{entry.name}</div>
              {!entry.directory && <div className="file-grid-size">{formatSize(entry.size)}</div>}
            </div>
          ))}
        </div>
      )}

      {dragOver && <div className="drop-overlay">Drop files to upload to {path}</div>}
    </div>
  );
}

// frontend/src/app/file-manager/file-manager-panel.component.ts
import { DatePipe } from '@angular/common';
import { Component, ElementRef, Input, OnInit, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { ApiService } from '../core/api.service';
import { FileEntry } from '../core/models';

type ViewMode = 'table' | 'grid';

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB', 'TB'];
  let value = bytes / 1024;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex++;
  }
  return `${value.toFixed(1)} ${units[unitIndex]}`;
}

@Component({
  selector: 'app-file-manager-panel',
  standalone: true,
  imports: [FormsModule, DatePipe],
  template: `
    <div
      class="file-manager"
      [class.file-manager-drag]="dragOver"
      (dragover)="onDragOver($event)"
      (dragleave)="dragOver = false"
      (drop)="onDrop($event)"
    >
      <div class="file-manager-toolbar">
        <button class="btn" type="button" [disabled]="path === '.' || path === '/'" (click)="navigateUp()">
          ↑ Up
        </button>
        <input class="file-manager-path" [(ngModel)]="path" (keydown.enter)="load()" />
        <input class="file-manager-search" placeholder="Search…" [(ngModel)]="search" (ngModelChange)="load()" />
        <button class="btn" type="button" (click)="fileInput.click()">Upload</button>
        <input #fileInput type="file" multiple hidden (change)="onFileInputChange($event)" />
        <button class="btn" type="button" [disabled]="selected.size === 0" (click)="downloadSelected()">
          Download ({{ selected.size }})
        </button>
        <div class="view-toggle">
          <button type="button" [class.active]="view === 'table'" (click)="view = 'table'">☰</button>
          <button type="button" [class.active]="view === 'grid'" (click)="view = 'grid'">▦</button>
        </div>
      </div>

      @if (uploadProgress) {
        <div class="upload-progress">
          <div
            class="upload-progress-bar"
            [style.width.%]="(uploadProgress.loaded / uploadProgress.total) * 100"
          ></div>
        </div>
      }

      @if (error) {
        <div class="form-error">{{ error }}</div>
      }
      @if (loading) {
        <div class="file-manager-loading">Loading…</div>
      }

      @if (!loading && view === 'table') {
        <table class="file-table">
          <thead>
            <tr>
              <th></th>
              <th>Name</th>
              <th>Size</th>
              <th>Modified</th>
              <th>Permissions</th>
            </tr>
          </thead>
          <tbody>
            @for (entry of entries; track entry.path) {
              <tr [class.row-selected]="selected.has(entry.path)" (dblclick)="navigateInto(entry)">
                <td>
                  <input
                    type="checkbox"
                    [checked]="selected.has(entry.path)"
                    (change)="toggleSelect(entry.path)"
                  />
                </td>
                <td>{{ entry.directory ? '📁' : '📄' }} {{ entry.name }}</td>
                <td>{{ entry.directory ? '—' : formatSize(entry.size) }}</td>
                <td>{{ entry.lastModified ? (entry.lastModified | date: 'medium') : '—' }}</td>
                <td>{{ entry.permissions }}</td>
              </tr>
            }
          </tbody>
        </table>
      }

      @if (!loading && view === 'grid') {
        <div class="file-grid">
          @for (entry of entries; track entry.path) {
            <div
              class="file-grid-item"
              [class.row-selected]="selected.has(entry.path)"
              (click)="toggleSelect(entry.path)"
              (dblclick)="navigateInto(entry)"
            >
              <div class="file-grid-icon">{{ entry.directory ? '📁' : '📄' }}</div>
              <div class="file-grid-name">{{ entry.name }}</div>
              @if (!entry.directory) {
                <div class="file-grid-size">{{ formatSize(entry.size) }}</div>
              }
            </div>
          }
        </div>
      }

      @if (dragOver) {
        <div class="drop-overlay">Drop files to upload to {{ path }}</div>
      }
    </div>
  `
})
export class FileManagerPanelComponent implements OnInit {
  @Input({ required: true }) environmentId!: string;
  @ViewChild('fileInput') fileInputRef!: ElementRef<HTMLInputElement>;

  path = '.';
  entries: FileEntry[] = [];
  loading = false;
  error: string | null = null;
  search = '';
  view: ViewMode = 'table';
  selected = new Set<string>();
  dragOver = false;
  uploadProgress: { loaded: number; total: number } | null = null;

  readonly formatSize = formatSize;

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.load();
  }

  async load(): Promise<void> {
    this.loading = true;
    this.error = null;
    try {
      this.entries = await firstValueFrom(this.api.listFiles(this.environmentId, this.path, this.search || undefined));
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Failed to list directory';
    } finally {
      this.loading = false;
      this.selected = new Set();
    }
  }

  navigateInto(entry: FileEntry): void {
    if (entry.directory) {
      this.path = entry.path;
      this.load();
    }
  }

  navigateUp(): void {
    if (this.path === '.' || this.path === '/') return;
    const trimmed = this.path.replace(/\/+$/, '');
    const parent = trimmed.substring(0, trimmed.lastIndexOf('/'));
    this.path = parent === '' ? '/' : parent;
    this.load();
  }

  toggleSelect(path: string): void {
    const next = new Set(this.selected);
    if (next.has(path)) next.delete(path);
    else next.add(path);
    this.selected = next;
  }

  onFileInputChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.uploadFiles(Array.from(input.files ?? []));
    input.value = '';
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
    this.dragOver = true;
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.dragOver = false;
    this.uploadFiles(Array.from(event.dataTransfer?.files ?? []));
  }

  async uploadFiles(files: File[]): Promise<void> {
    if (files.length === 0) return;
    this.uploadProgress = { loaded: 0, total: 1 };
    try {
      await new Promise<void>((resolve, reject) => {
        this.api.uploadFiles(this.environmentId, this.path, files).subscribe({
          next: (progress) => {
            this.uploadProgress = { loaded: progress.loaded, total: progress.total };
            if (progress.done) resolve();
          },
          error: reject
        });
      });
      await this.load();
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Upload failed';
    } finally {
      this.uploadProgress = null;
    }
  }

  downloadSelected(): void {
    this.entries
      .filter((entry) => this.selected.has(entry.path) && !entry.directory)
      .forEach((entry) => {
        const a = document.createElement('a');
        a.href = this.api.downloadUrl(this.environmentId, entry.path);
        a.download = entry.name;
        a.click();
      });
  }
}
