// frontend/src/components/Environments/EnvironmentItem.tsx
import type { ConnectionStatus, Environment } from "../../types";

interface Props {
  environment: Environment;
  status?: ConnectionStatus;
  selected: boolean;
  onSelect: () => void;
  onEdit: () => void;
  onDuplicate: () => void;
  onDelete: () => void;
}

const STATE_LABEL: Record<string, string> = {
  CONNECTED: "Connected",
  CONNECTING: "Connecting…",
  RECONNECTING: "Reconnecting…",
  ERROR: "Error",
  DISCONNECTED: "Disconnected"
};

export default function EnvironmentItem({ environment, status, selected, onSelect, onEdit, onDuplicate, onDelete }: Props) {
  const state = status?.state ?? "DISCONNECTED";

  return (
    <div className={`env-item ${selected ? "env-item-selected" : ""}`} onClick={onSelect}>
      <span className={`health-dot health-${state.toLowerCase()}`} title={STATE_LABEL[state]} />
      <div className="env-item-info">
        <div className="env-item-name">
          {environment.name}
          <span className={`env-badge env-badge-${environment.type.toLowerCase()}`}>{environment.type}</span>
        </div>
        <div className="env-item-detail">
          {environment.username}@{environment.serverIp || "not set"}:{environment.sshPort}
        </div>
      </div>
      <div className="env-item-actions" onClick={(e) => e.stopPropagation()}>
        <button className="icon-btn" title="Edit" onClick={onEdit}>
          ✎
        </button>
        <button className="icon-btn" title="Duplicate" onClick={onDuplicate}>
          ⎘
        </button>
        <button className="icon-btn" title="Delete" onClick={onDelete}>
          ✕
        </button>
      </div>
    </div>
  );
}

// frontend/src/app/environments/environment-item.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { ConnectionStatus, Environment } from '../core/models';

const STATE_LABEL: Record<string, string> = {
  CONNECTED: 'Connected',
  CONNECTING: 'Connecting…',
  RECONNECTING: 'Reconnecting…',
  ERROR: 'Error',
  DISCONNECTED: 'Disconnected'
};

@Component({
  selector: 'app-environment-item',
  standalone: true,
  template: `
    <div class="env-item" [class.env-item-selected]="selected" (click)="select.emit()">
      <span class="health-dot" [class]="'health-' + state().toLowerCase()" [title]="stateLabel()"></span>
      <div class="env-item-info">
        <div class="env-item-name">
          {{ environment.name }}
          <span class="env-badge" [class]="'env-badge-' + environment.type.toLowerCase()">{{ environment.type }}</span>
        </div>
        <div class="env-item-detail">
          {{ environment.username }}&#64;{{ environment.serverIp || 'not set' }}:{{ environment.sshPort }}
        </div>
      </div>
      <div class="env-item-actions" (click)="$event.stopPropagation()">
        <button class="icon-btn" type="button" title="Edit" (click)="edit.emit()">✎</button>
        <button class="icon-btn" type="button" title="Duplicate" (click)="duplicate.emit()">⎘</button>
        <button class="icon-btn" type="button" title="Delete" (click)="delete.emit()">✕</button>
      </div>
    </div>
  `
})
export class EnvironmentItemComponent {
  @Input({ required: true }) environment!: Environment;
  @Input() status?: ConnectionStatus;
  @Input() selected = false;
  @Output() select = new EventEmitter<void>();
  @Output() edit = new EventEmitter<void>();
  @Output() duplicate = new EventEmitter<void>();
  @Output() delete = new EventEmitter<void>();

  state(): string {
    return this.status?.state ?? 'DISCONNECTED';
  }

  stateLabel(): string {
    return STATE_LABEL[this.state()] ?? this.state();
  }
}
