// frontend/src/components/Environments/EnvironmentFormModal.tsx
import { useState } from "react";
import { useAppContext } from "../../context/AppContext";
import type { EnvironmentFormState } from "../Layout/AppShell";
import type { EnvironmentRequest, EnvironmentType } from "../../types";
import Modal from "../common/Modal";

interface Props {
  state: NonNullable<EnvironmentFormState>;
  onClose: () => void;
}

export default function EnvironmentFormModal({ state, onClose }: Props) {
  const { createEnvironment, updateEnvironment } = useAppContext();
  const editing = state.mode === "edit";
  const initial = editing ? state.environment : null;

  const [name, setName] = useState(initial?.name ?? "");
  const [type, setType] = useState<EnvironmentType>(initial?.type ?? "CUSTOM");
  const [serverIp, setServerIp] = useState(initial?.serverIp ?? "");
  const [sshPort, setSshPort] = useState(initial?.sshPort ?? 22);
  const [ppkPath, setPpkPath] = useState(initial?.ppkPath ?? "");
  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);
    setSubmitting(true);
    const request: EnvironmentRequest = { name, type, serverIp, sshPort, ppkPath };
    try {
      if (editing) {
        await updateEnvironment(initial!.id, request);
      } else {
        await createEnvironment(request);
      }
      onClose();
    } catch (err) {
      setFormError(err instanceof Error ? err.message : "Failed to save environment");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Modal title={editing ? "Edit Environment" : "New Environment"} onClose={onClose}>
      <form onSubmit={handleSubmit} className="form">
        <label className="form-field">
          <span>Name</span>
          <input value={name} onChange={(e) => setName(e.target.value)} required autoFocus />
        </label>

        <label className="form-field">
          <span>Type</span>
          <select value={type} onChange={(e) => setType(e.target.value as EnvironmentType)}>
            <option value="DEV">DEV</option>
            <option value="UAT">UAT</option>
            <option value="CUSTOM">CUSTOM</option>
          </select>
        </label>

        <label className="form-field">
          <span>Server IP</span>
          <input value={serverIp} onChange={(e) => setServerIp(e.target.value)} placeholder="10.0.0.5" required />
        </label>

        <label className="form-field">
          <span>SSH Port</span>
          <input
            type="number"
            min={1}
            max={65535}
            value={sshPort}
            onChange={(e) => setSshPort(Number(e.target.value))}
            required
          />
        </label>

        <label className="form-field">
          <span>PPK Path</span>
          <input
            value={ppkPath}
            onChange={(e) => setPpkPath(e.target.value)}
            placeholder="/path/to/key.ppk"
            required
          />
        </label>

        <label className="form-field">
          <span>Username</span>
          <input value={initial?.username ?? "hadoop"} disabled />
        </label>

        {formError && <div className="form-error">{formError}</div>}

        <div className="form-actions">
          <button type="button" className="btn" onClick={onClose}>
            Cancel
          </button>
          <button type="submit" className="btn btn-primary" disabled={submitting}>
            {editing ? "Save" : "Create"}
          </button>
        </div>
      </form>
    </Modal>
  );
}

// frontend/src/app/environments/environment-form-modal.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ModalComponent } from '../shared/modal.component';
import { AppStateService } from '../core/app-state.service';
import { Environment, EnvironmentRequest, EnvironmentType } from '../core/models';

@Component({
  selector: 'app-environment-form-modal',
  standalone: true,
  imports: [FormsModule, ModalComponent],
  template: `
    <app-modal [title]="editing ? 'Edit Environment' : 'New Environment'" (close)="close.emit()">
      <form class="form" (ngSubmit)="submit()">
        <label class="form-field">
          <span>Name</span>
          <input name="name" [(ngModel)]="name" required autofocus />
        </label>

        <label class="form-field">
          <span>Type</span>
          <select name="type" [(ngModel)]="type">
            <option value="DEV">DEV</option>
            <option value="UAT">UAT</option>
            <option value="CUSTOM">CUSTOM</option>
          </select>
        </label>

        <label class="form-field">
          <span>Server IP</span>
          <input name="serverIp" [(ngModel)]="serverIp" placeholder="10.0.0.5" required />
        </label>

        <label class="form-field">
          <span>SSH Port</span>
          <input name="sshPort" type="number" min="1" max="65535" [(ngModel)]="sshPort" required />
        </label>

        <label class="form-field">
          <span>PPK Path</span>
          <input name="ppkPath" [(ngModel)]="ppkPath" placeholder="/path/to/key.ppk" required />
        </label>

        <label class="form-field">
          <span>Username</span>
          <input name="username" [value]="environment?.username ?? 'hadoop'" disabled />
        </label>

        @if (formError) {
          <div class="form-error">{{ formError }}</div>
        }

        <div class="form-actions">
          <button type="button" class="btn" (click)="close.emit()">Cancel</button>
          <button type="submit" class="btn btn-primary" [disabled]="submitting">
            {{ editing ? 'Save' : 'Create' }}
          </button>
        </div>
      </form>
    </app-modal>
  `
})
export class EnvironmentFormModalComponent implements OnInit {
  @Input() mode: 'create' | 'edit' = 'create';
  @Input() environment?: Environment;
  @Output() close = new EventEmitter<void>();

  name = '';
  type: EnvironmentType = 'CUSTOM';
  serverIp = '';
  sshPort = 22;
  ppkPath = '';
  submitting = false;
  formError: string | null = null;

  constructor(private state: AppStateService) {}

  get editing(): boolean {
    return this.mode === 'edit';
  }

  ngOnInit(): void {
    if (this.environment) {
      this.name = this.environment.name;
      this.type = this.environment.type;
      this.serverIp = this.environment.serverIp;
      this.sshPort = this.environment.sshPort;
      this.ppkPath = this.environment.ppkPath;
    }
  }

  async submit(): Promise<void> {
    this.formError = null;
    this.submitting = true;
    const request: EnvironmentRequest = {
      name: this.name,
      type: this.type,
      serverIp: this.serverIp,
      sshPort: Number(this.sshPort),
      ppkPath: this.ppkPath
    };
    try {
      if (this.editing && this.environment) {
        await this.state.updateEnvironment(this.environment.id, request);
      } else {
        await this.state.createEnvironment(request);
      }
      this.close.emit();
    } catch (e) {
      this.formError = e instanceof Error ? e.message : 'Failed to save environment';
    } finally {
      this.submitting = false;
    }
  }
}
