// frontend/src/app/terminal/tab-strip.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Tab } from '../core/models';

@Component({
  selector: 'app-tab-strip',
  standalone: true,
  template: `
    <div class="tab-strip">
      @for (tab of tabs; track tab.id) {
        <div
          class="tab-strip-item"
          [class.tab-strip-item-active]="tab.id === activeTabId"
          (click)="select.emit(tab.id)"
        >
          <span class="tab-strip-icon">{{ tab.type === 'terminal' ? '⌨' : '📁' }}</span>
          <span class="tab-strip-title">{{ tab.title }}</span>
          <button class="tab-strip-close" type="button" (click)="onClose($event, tab.id)">✕</button>
        </div>
      }
    </div>
  `
})
export class TabStripComponent {
  @Input({ required: true }) tabs: Tab[] = [];
  @Input() activeTabId: string | null = null;
  @Output() select = new EventEmitter<string>();
  @Output() close = new EventEmitter<string>();

  onClose(event: MouseEvent, id: string): void {
    event.stopPropagation();
    this.close.emit(id);
  }
}

// frontend/src/components/Terminal/TabStrip.tsx
import type { Tab } from "../../types";

interface Props {
  tabs: Tab[];
  activeTabId: string | null;
  onSelect: (id: string) => void;
  onClose: (id: string) => void;
}

export default function TabStrip({ tabs, activeTabId, onSelect, onClose }: Props) {
  return (
    <div className="tab-strip">
      {tabs.map((tab) => (
        <div
          key={tab.id}
          className={`tab-strip-item ${tab.id === activeTabId ? "tab-strip-item-active" : ""}`}
          onClick={() => onSelect(tab.id)}
        >
          <span className="tab-strip-icon">{tab.type === "terminal" ? "⌨" : "📁"}</span>
          <span className="tab-strip-title">{tab.title}</span>
          <button
            className="tab-strip-close"
            onClick={(e) => {
              e.stopPropagation();
              onClose(tab.id);
            }}
          >
            ✕
          </button>
        </div>
      ))}
    </div>
  );
}
